<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>  
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <title>Idées cadeaux</title>
        <link rel="shortcut icon" href="<?php echo ROOT_TO_PUBLIC; ?>/image/cadeaux.ico"/>
        <link rel="stylesheet" type="text/css" href="<?php echo ROOT_TO_PUBLIC; ?>/css/common.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo ROOT_TO_PUBLIC; ?>/css/normal/global.css" />
    </head> 
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>